"""
evaluate_model.py — Evaluate model accuracy and update model_accuracy.json

Run this script after setting up your test data to update the accuracy
displayed in the web application's top bar.

Usage:
    python evaluate_model.py
"""

import json
import os
import sys
from pathlib import Path

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# ─── Configuration ────────────────────────────────────────────────────────────
MODEL_PATH   = "mobilenetv2_best_model.keras"   # evaluation model
TEST_DATA    = "data/clahe_balanced/test"              # test set directory
OUTPUT_JSON  = "model_accuracy.json"
IMG_SIZE     = (224, 224)
BATCH_SIZE   = 32


def evaluate():
    if not os.path.exists(MODEL_PATH):
        print(f"[ERROR] Model not found: {MODEL_PATH}")
        print("Copy your model to models/ and update MODEL_PATH in this script.")
        sys.exit(1)

    if not os.path.exists(TEST_DATA):
        print(f"[ERROR] Test data not found: {TEST_DATA}")
        print(f"Expected directory structure: {TEST_DATA}/NORMAL/ and {TEST_DATA}/PNEUMONIA/")
        sys.exit(1)

    print(f"[INFO] Loading model: {MODEL_PATH}")
    model = tf.keras.models.load_model(MODEL_PATH)

    test_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)
    test_gen = test_datagen.flow_from_directory(
        TEST_DATA,
        target_size  = IMG_SIZE,
        batch_size   = BATCH_SIZE,
        class_mode   = "binary",
        shuffle      = False,
        color_mode   = "rgb",
    )

    print("[INFO] Evaluating model…")
    loss, accuracy = model.evaluate(test_gen, verbose=1)

    acc_pct = round(accuracy * 100, 2)
    print(f"\n✅ Balanced MobileNetV2 Test Accuracy: {acc_pct}%")

    result = {
        "accuracy":     acc_pct,
        "loss":         round(loss, 4),
        "model_name":   os.path.basename(MODEL_PATH),
        "evaluated_on": TEST_DATA,
        "samples":      test_gen.samples,
        "note":         "Auto-generated by evaluate_model.py",
    }

    with open(OUTPUT_JSON, "w") as f:
        json.dump(result, f, indent=2)

    print(f"✅ Saved accuracy to {OUTPUT_JSON}")
    return result


if __name__ == "__main__":
    evaluate()
